-- Qualizenz Supabase/PostgreSQL schema.
-- Environment-based admin auth is supported in app.py; admin_users is optional for future DB auth.

CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    is_visible BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS articles (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE,
    category TEXT,
    description TEXT,
    summary TEXT,
    content TEXT,
    author TEXT DEFAULT 'Qualizenz Team',
    publish_date DATE,
    status TEXT DEFAULT 'draft',
    is_visible BOOLEAN DEFAULT TRUE,
    featured_image TEXT,
    image_path TEXT,
    file_path TEXT,
    seo_meta_title TEXT,
    seo_meta_description TEXT,
    keywords TEXT,
    related_articles TEXT,
    call_to_action TEXT,
    price NUMERIC(10, 2),
    is_free BOOLEAN DEFAULT TRUE,
    view_count INTEGER DEFAULT 0,
    download_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sop_templates (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    description TEXT,
    content TEXT,
    file_type TEXT,
    file_path TEXT,
    image_path TEXT,
    price NUMERIC(10, 2),
    is_free BOOLEAN DEFAULT FALSE,
    is_visible BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'draft',
    preview_url TEXT,
    download_url TEXT,
    purchase_url TEXT,
    download_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS validation_templates (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    description TEXT,
    content TEXT,
    file_type TEXT,
    file_path TEXT,
    image_path TEXT,
    price NUMERIC(10, 2),
    is_free BOOLEAN DEFAULT FALSE,
    is_visible BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'draft',
    preview_url TEXT,
    download_url TEXT,
    purchase_url TEXT,
    download_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS free_resources (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    description TEXT,
    content TEXT,
    file_type TEXT,
    file_path TEXT,
    image_path TEXT,
    price NUMERIC(10, 2) DEFAULT 0,
    is_free BOOLEAN DEFAULT TRUE,
    is_visible BOOLEAN DEFAULT TRUE,
    status TEXT DEFAULT 'draft',
    download_url TEXT,
    email_capture_required BOOLEAN DEFAULT TRUE,
    download_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS homepage_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_title TEXT,
    hero_subtitle TEXT,
    hero_intro TEXT,
    announcement_text TEXT,
    announcement_visible BOOLEAN DEFAULT TRUE,
    consulting_text TEXT,
    contact_email TEXT,
    whatsapp_link TEXT,
    footer_disclaimer TEXT,
    featured_resources JSONB DEFAULT '[]'::jsonb,
    visible_sections JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT UNIQUE NOT NULL,
    setting_value JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS consulting_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    country TEXT,
    company TEXT,
    service_required TEXT,
    message TEXT,
    uploaded_document_url TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    topic TEXT,
    message TEXT,
    status TEXT DEFAULT 'new',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    source TEXT,
    status TEXT DEFAULT 'subscribed',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS downloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_type TEXT,
    resource_id TEXT,
    filename TEXT,
    email TEXT,
    ip_address TEXT,
    user_agent TEXT,
    downloaded_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS website_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT,
    page_url TEXT,
    resource_type TEXT,
    resource_id TEXT,
    referrer TEXT,
    user_agent TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
